#!/usr/bin/env python3
"""Generate a C++ header with raw RGBA icon data for glfwSetWindowIcon.

Usage: gen_icon_data.py <input.ico> <output.h> [--sizes 16 32 48 64 128]

Requires Pillow (pip install pillow).
"""
import argparse
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("gen_icon_data.py: Pillow is required (pip install pillow)")

BYTES_PER_LINE = 24


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("ico", help="input .ico file")
    parser.add_argument("output", help="output C++ header")
    parser.add_argument("--sizes", type=int, nargs="+", default=[16, 32, 48, 64, 128],
                        help="square icon sizes to embed (each must exist in the .ico)")
    args = parser.parse_args()

    ico = Image.open(args.ico)
    available = sorted(s[0] for s in ico.info.get("sizes", []))

    out = [
        "#pragma once",
        "// Generated by resources/gen_icon_data.py from app.ico. Do not edit by hand.",
        "// Raw RGBA8 pixels, row-major, top-left origin (format expected by glfwSetWindowIcon).",
        "#include <cstdint>",
        "",
        "namespace kubvc::application::icon_data {",
    ]
    for size in args.sizes:
        if size not in available:
            sys.exit(f"gen_icon_data.py: {size}x{size} not found in {args.ico} "
                     f"(available: {available})")
        data = ico.ico.getimage((size, size)).convert("RGBA").tobytes()
        out.append(f"    inline constexpr std::uint8_t k{size}x{size}[] = {{")
        for i in range(0, len(data), BYTES_PER_LINE):
            out.append("        " + ",".join(str(b) for b in data[i:i + BYTES_PER_LINE]) + ",")
        out.append("    };")
    out.append("}")

    with open(args.output, "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
